site_name: PAUF
site_description: Programación de Aplicaciones utilizando Frameworks

theme:
  name: material
  language: es

nav:
  - Inicio: index.md
  - "Unidad 1 - Fundamentos de Python":
      - Introducción: unidad1/index.md
      - Variables y operadores: unidad1/variables-operadores.md
      - Condicionales: unidad1/condicionales.md
      - Bucles: unidad1/bucles.md
      - Programación orientada a objetos: unidad1/poo.md